import Button from '@/components/Button'
import HeaderComponent from '@/components/Header'
import SearchInput from '@/components/SearchInput'
import Title from '@/components/Title'
import { styled } from '@/styles'
import Head from 'next/head'

const Container = styled('main', {
  padding: '0px 15px'
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Rick and morty</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HeaderComponent />
        <Container>
          <Title>Busque por um personagem</Title>
          <SearchInput />
          <Button>Buscar</Button>
        </Container>
      </main>
    </>
  )
}
