import HeaderComponent from '@/components/header'
import Title from '@/components/Title'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Rick and morty</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HeaderComponent />
        <Title />
      </main>
    </>
  )
}
